name: Databricks Model Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Databricks CLI
      run: |
        pip install databricks-cli
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
        echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

    - name: Upload Notebooks
      run: |
        databricks workspace mkdirs /Shared/mymode
        databricks workspace import mymode/notebooks/build_model.py /Shared/mymode/build_model -f SOURCE -l PYTHON -o
        databricks workspace import mymode/notebooks/batc_prediction.py /Shared/mymode/batch_prediction -f SOURCE -l PYTHON -o

    - name: Run Notebooks
      run: |
        databricks runs submit --json '{
          "run_name": "Run build_model",
          "new_cluster": {
            "spark_version": "13.3.x-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 1
          },
          "notebook_task": {
            "notebook_path": "/Shared/mymode/build_model"
          }
        }'

        databricks runs submit --json '{
          "run_name": "Run batch_prediction",
          "new_cluster": {
            "spark_version": "13.3.x-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 1
          },
          "notebook_task": {
            "notebook_path": "/Shared/mymode/batch_prediction"
          }
        }'
